### ISSUE TITLE
Cenário 3 não é satisfeito

### ISSUE THREAD

**Issue by rafaelcorsi** [LiuSeeker/aps2-embarcados#13]
Vó Hilda, contra sua vontade, foi forçada a trocar de máquina de lavar roupas após a sua praticamente desmontar de tanto uso. Com a nova máquina instalada pelo técnico, coloca as roupas e os produtos de limpeza dentro da máquina e cicla pelos modos de lavagem até encontrar uma opção que a agrade (passa varias vezes por todos os modos até decidir qual irá usar). **Como tem dificuldade de leitura repara nos ícones para entender a configuração que mais a agrada.**

https://github.com/Insper/ComputacaoEmbarcada/wiki/APS-2-Interface#cenário-3

**Comment by LiuSeeker** [comment]
Resolvido colocando icones coloridos e descrição de cada botão
https://github.com/LiuSeeker/aps2-embarcados/commit/49771f47ebe4827b5d9897a86b659cd3b2da2e52
